export default function TheFooter() {
  return (
    <footer className="flex flex-col gap-4 lg:flex-row lg:items-end justify-between text-forgeBrown p-5">
      <p id="disclaimer" className="font-medium lg:w-1/3">
        Disclaimer: All renders on this website have been generated by
        artificial intelligence and are for illustrative purposes only. Images
        will soon be replaced with high-quality photography as part of our
        upcoming building remodel.
      </p>
      <p className="text-lg font-medium">© 2024 The Forge</p>
    </footer>
  );
}
