import SocialIcons from "./SocialIcons";
import Link from "next/link";

export default function TheFooter() {
  return (
    <footer className="flex flex-col gap-4 lg:flex-row lg:items-stretch text-black p-2 border-t-8 border-new-light">
      {/* Left - Disclaimer */}
      <div className="w-full lg:w-2/5">
        <p id="disclaimer" className="text-sm lg:text-md">
          Disclaimer: A portion of the renders on this website have been generated by
          artificial intelligence and are for illustrative purposes only. Images
          will soon be replaced with high-quality photography as part of our
          upcoming building remodel.
        </p>
      </div>

      {/* Center - Social Icons */}
      <div className="w-full lg:w-1/5 flex flex-col h-full gap-2 items-center justify-center self-center text-center">
        <SocialIcons placement="footer" />
        <p className="text-lg">© 2025 The Forge</p>
      </div>

      {/* Right - Links */}
      <div className="w-full lg:w-2/5 flex flex-col items-center lg:items-end justify-end gap-2 text-right pr-0 lg:pr-16">
        <Link href="/terms" className="py-2">
          <p className="text-sm">Terms of Service</p>
        </Link>
        <Link href="/privacy" className="py-2">
          <p className="text-sm">Privacy Policy</p>
        </Link>
      </div>
    </footer>
  );
}
