import { Sofia_Sans } from "next/font/google";
import "./globals.css";

const sofiaSans = Sofia_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "The Forge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`min-h-svh flex flex-col mx-auto relative ${sofiaSans.className}`}
      >
        {children}
      </body>
    </html>
  );
}
